title: "PolandballHub"
description: "ポーランドボールがテーマのWebアプリ！便利ツールの詰め合わせ"
url: "https://PolandBallHub-Operator.github.io"
baseurl: "/pbhub"

theme: null

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title+/

include:
  - manifest.json
  - sw.js
  - .nojekyll

exclude:
  - node_modules
  - .git
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

output: web
safe: false
lsi: false
future: false

plugins: []
